config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  get 'about', to: 'articles#about'
  # get 'contact', to: 'articles#contact'
  get 'portfolio', to: 'articles#portfolio'
  get 'policy', to: 'articles#policy'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to:'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def portfolio
  end

  def policy
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.sned_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  def done
  end
  # 送信完了画面で使う

  private

  def contact_params
    params.require(:contact)
          .permit(:email,
                  :name,
                  :subject,
                  :message
                  )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/articles/about.html.erb
<%= render 'shared/header'%>
<div class="about-main">
  <div class="about-content">
    <h2 class="about">About Us</h2>
    <p class="about-message">
      こんにちは、”WinGs”代表の伊藤瑞基です。<br>
      "WinGs"はWebサイト制作、Webライティングを主に扱います。<br>
      ブログ制作代行も承っております。<br>
      お気軽にご連絡ください。
    </p>
    <p class="port-btn">
      <%= link_to 'Portfolio', portfolio_path, class:"btn btn-outline-primary"%>
    </p>
  </div>
</div>
<%= render 'shared/footer'%>

app/views/articles/index.html.erb
<%= render 'shared/header'%>
<div class="main">
  <div class="main-content">
    <h1 class="index-philosophy">夢を形に、想いを届ける</h1>
    <p class="index-message top">
      <b>Webサイト制作グループ”WinGs”へようこそ。</b>
    </p>
    <p class="index-message second">
      素敵なアイディア、想い、夢<br>
      皆様の理想を人々に発信する。<br>
      それが我々の使命であり存在意義です。
    </p>
  </div>
  
</div>
<%= render 'shared/footer'%>

app/views/articles/plan.html.erb
<%= render 'shared/header'%>
<div class="plan-main">
  <h2>Plan</h2>
</div>
<%= render 'shared/footer'%>

app/views/articles/policy.html.erb
<%= render 'shared/header'%>
<div class="policy-main">
  <h3>プライバシーポリシー(個人情報保護方針)</h3>

  <div class="sent">
    <h3>利用規約</h3>
    <p>
      WinGs（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
    </p>
  </div>

  <div class="sent">
    <h3>第1条（個人情報）</h3>
    <p>
      個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
    </p>
  </div>

  <div class="sent">
    <h3>第2条（個人情報の収集方法）</h3>
    <p>
      当社は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。
    </p>
  </div>

  <div class="sent">
    <h3>第3条（個人情報を収集・利用する目的）</h3>
    <p>
      当社が個人情報を収集・利用する目的は，以下のとおりです。<br>
      当社サービスの提供・運営のため<br>
      ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）<br>
      ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当社が提供する他のサービスの案内のメールを送付するため<br>
      メンテナンス，重要なお知らせなど必要に応じたご連絡のため<br>
      利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため<br>
      ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため<br>
      有料サービスにおいて，ユーザーに利用料金を請求するため<br>
      上記の利用目的に付随する目的
    </p>
  </div>

  <div class="sent">
    <h3>第4条（利用目的の変更）</h3>
    <p>
      当社は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。<br>
      利用目的の変更を行った場合には，変更後の目的について，当社所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。
    </p>
  </div>

  <div class="sent">
    <h3>第5条（個人情報の第三者提供）</h3>
    <p>
      当社は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。<br>
      ただし，個人情報保護法その他の法令で認められる場合を除きます。<br>
      ・人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき<br>
      ・公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき<br>
      ・国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき<br>
      ・予め次の事項を告知あるいは公表し，かつ当社が個人情報保護委員会に届出をしたとき<br>
      ・利用目的に第三者への提供を含むこと<br>
      ・第三者に提供されるデータの項目<br>
      ・第三者への提供の手段または方法<br>
      ・本人の求めに応じて個人情報の第三者への提供を停止すること<br>
      前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。<br>
      ・当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合<br>
      ・合併その他の事由による事業の承継に伴って個人情報が提供される場合<br>
      ・個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合
  </div>

  <div class="sent">
    <h3>第6条（個人情報の開示）</h3>
    <p>
      当社は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。<br>
      ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。<br>
      なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。<br>
      ・本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合<br>
      ・当社の業務の適正な実施に著しい支障を及ぼすおそれがある場合<br>
      ・その他法令に違反することとなる場合<br>
      前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。
    </p>
  </div>

  <div class="sent">
    <h3>第7条（個人情報の訂正および削除）</h3>
    <p>
      ユーザーは，当社の保有する自己の個人情報が誤った情報である場合には，当社が定める手続きにより，当社に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。<br>
      当社は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。<br>
      当社は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。
    </p>
  </div>

  <div class="sent">
    <h3>第8条（個人情報の利用停止等）</h3>
    <p>
      当社は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。<br>
      前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。<br>
      当社は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。<br>
      前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。
    </p>
  </div>
  <div class="sent">
    <h3>第9条（プライバシーポリシーの変更）</h3>
    <p>
      本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。<br>
      当社が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。
    </p>
  </div>
  <div class="sent">
    <h3>第10条（お問い合わせ窓口）</h3>
    <p>
      本ポリシーに関するお問い合わせは，下記の窓口(お問い合わせフォーム)までお願いいたします。<br>
    </p>
    <p class="contact-btn">
      <%= link_to 'お問い合せ', new_contact_path, class:"btn btn-outline-primary"%>
    </p>

    <p>以上</p>
  </div>

</div>
<%= render 'shared/footer'%>

app/views/articles/portfolio.html.erb
<%= render 'shared/header'%>
<div class="portfolio-main">
  <h2 class="port">Portfolio</h2>

    <div class="col">
      <div class="card">
        <%= image_tag 'nomad_diary.jpeg', class:"nomad-diary", alt:"nomad-diary"%>
        <h5 class="card-title">ノマド日記</h5>
        <p class="card-text">
          アウトドア情報を中心に発信するブログ<br>
          主にワードプレスで構成、編集しています。
        </p>
        <div class="btn">
          <%= link_to 'Show!', 'https://mizu1228.com/', class:"btn btn-primary"%>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card">
        <%= image_tag 'nomad_diary.jpeg', class:"nomad-diary", alt:"nomad-diary"%>
        <h5 class="card-title">Campary.</h5>
        <p class="card-text">
          アウトドアに特化した新しいSNSを提案<br>
          主にRubyOnRailsで構成、編集しています。
        </p>
        <div class="btn">
          <%= link_to 'Show!', '#', class:"btn btn-primary"%>
        </div>
      </div>
    </div>
</div>
<%= render 'shared/footer'%>

app/views/contacts/canfirm.html.erb
<table>
  <tbody>
    <tr>
      <td class="text-center" style="width 30%;">お名前</td>
      <td><%= @contact.name %></td>
    </tr>
    <tr>
      <td class="text-center">メッセージ</td>
      <td style="white-space: pre-wrap;"><%= @contact.message %></td>
    </tr>
  </tbody>
</table>

<%= form_for(@contact) do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :subject %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '送信' %></div>
<% end %>
<%= form_for @contact, url: back_path do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :subject %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '入力画面に戻る' %></div>
<% end %>

app/views/contacts/new.html.erb
<%= render 'shared/header'%>
<div class="contact-main">
  <h2 class="contact-mt">Contact</h2>
  <p class="contact-st text-secondary">- お問い合わせ -</p>
  <p>
    WinGs に関心をお寄せいただきありがとうございます。<br>
    お問い合わせ内容を以下フォームを記入のうえ送信願います。<br>
    内容を確認して担当者より連絡を差し上げます。
  </p>

  <%= form_for(@contact, url: confirm_path) do |f| %>
    <div class="form-group" id="form-mini">
      <%= f.label :name, 'お名前*' %>
      <%= f.text_field :name, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group" id="form-mini">
      <%= f.label :email, 'メールアドレス*' %>
      <%= f.text_field :email, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group" id="form-mes">
      <%= f.label :message, 'メッセージ*' %>
      <%= f.text_area :message, size: '10x10', class: 'form-control' %>
    </div>

    <div class="btn" id="contact-btn">
      <%= f.submit '送信する', class:"btn btn-primary" %>
    </div>
  <% end %>
</div>
<%= render 'shared/footer'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WinGs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer-bar">
  <%= image_tag 'logo.png', class:"footer-logo", alt:"WinGs"%>
  <div class="footer-right">
    <%= link_to "お問い合わせ", new_contact_path, class:"link-secondary footer-contact" %>
    <%= link_to "運営ポリシー", policy_path, class:"link-secondary footer-policy"%>
    <p class="copy-right">2022 ©︎ WinGs</p>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header-main">
<div class="header-bar">
  <div class="header-logo">
    <%= link_to root_path do %>
      <%= image_tag "logo.png", class:"wings-logo",alt:"WinGs"%>
    <% end %>
  </div>
  <div class="header-menu">
    <%= link_to 'Portfolio', portfolio_path, class:"link-secondary menu portfolio"%>
    <%= link_to 'About Us', about_path, class:"link-secondary menu about"%>
    <%= link_to 'Contact', new_contact_path, class:"link-secondary menu contact"%>
  </div>
</div>
</div>